openai_api_key = "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"
serpapi_api_key = "850f148f69546f7576ef55d3e04f742897cf5af77175fd0f1479adedd8dbdaaf"
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
EMBEDDING_SIZE = 1536
MODEL_NAME = "gpt-4-0613"
TODO_CHAIN_MODEL_NAME = "gpt-4-0613"
BABY_AGI_MODEL_NAME = "gpt-4-0613"
STABILITY_KEY = "sk-7ROBgZSdxCBOlpi7xe5XpJNDQx3fn2LSc79fHLDNnkst2caT"
BING_SUBSCRIPTION_KEY = "e1364124955e49c7b6e7724cc9a5e3d3"
BING_SEARCH_URL = "https://api.bing.microsoft.com/v7.0/search"
WOLFRAM_ALPHA_APPID = "TTGQ2Y-4VRPX7HPGJ"
GOOGLE_API_KEY = "AIzaSyBvAddRD-RDku91YAoa5LbV776ingmVlM8"
GPLACES_API_KEY = "AIzaSyBvAddRD-RDku91YAoa5LbV776ingmVlM8"
GOOGLE_CSE_ID = "33ccc2f56efb6473a"
ELEVEN_LABS_API_KEY = "4667d3f5857a2d093c44bedb70c43d15"
ELEVEN_LABS_VOICE_ID = "8OgC0uF6ItlmsodvjmTO/stream"